listen_addr = "0.0.0.0:8080"
data_dir = "/home/zhourui/opensource/ostool-pr/.ostool-server"
board_dir = "/home/zhourui/opensource/ostool-pr/.ostool-server/boards"

[lease]
default_ttl_secs = 900
max_ttl_secs = 3600
gc_interval_secs = 30

[tftp]
provider = "system_tftpd_hpa"
enabled = true
root_dir = "/srv/tftp"
config_path = "/etc/default/tftpd-hpa"
service_name = "tftpd-hpa"
username = "tftp"
address = ":69"
options = "-l -s -c"
manage_config = false
reconcile_on_start = true
