[package]
authors = ["柏乔森 <baiqiaosen@gmail.com>"]
categories = ["embedded", "development-tools"]
description = "Shared HTTP Boot protocol types and parsers"
edition = "2024"
keywords = ["httpboot", "uefi", "bootloader"]
license = "MIT OR Apache-2.0"
name = "httpboot-protocol"
repository = "https://github.com/drivercraft/ostool"
version = "0.4.1"

[features]
default = ["std", "json"]
alloc = []
json = ["alloc", "dep:serde", "dep:serde_json"]
std = ["alloc", "serde?/std", "serde_json?/std"]

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"], optional = true }
serde_json = { version = "1", default-features = false, features = ["alloc"], optional = true }
