name: Quality Check

on:
  workflow_call:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [stable]
        targets: [x86_64-unknown-linux-gnu]
        
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: pnpm/action-setup@v5.0.0
      with:
        version: 10.33.0
        run_install: false
    - uses: actions/setup-node@v6.3.0
      with:
        node-version: 24
        cache: pnpm
        cache-dependency-path: ostool-server/webui/pnpm-lock.yaml
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: clippy, rustfmt
        targets: ${{ matrix.targets }}
    - uses: Swatinem/rust-cache@v2.9.1
    - name: Install qemu
      run: |
        sudo apt-get update
        sudo apt install qemu-system-aarch64 -y
        sudo apt install u-boot-tools -y
    - name: Install lib libudev-dev
      run: sudo apt install libudev-dev -y
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --target ${{ matrix.targets }} --all-features
    - name: Build
      run: cargo build --target ${{ matrix.targets }} --all-features
    - name: Unit test
      if: ${{ matrix.targets == 'x86_64-unknown-linux-gnu' }}
      run: cargo test --target ${{ matrix.targets }} -- --nocapture
