name: Release

on:
  workflow_run:
    workflows: ["Quality Check"]
    branches: [main]
    types: [completed]

permissions: {}

jobs:
  release-plz-release:
    name: Release-plz release
    if: &release_condition ${{ github.repository_owner == 'drivercraft' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - &setup-libudenv
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: libudev-dev
          version: 1.0
      - &setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v5.0.0
        with:
          version: 10.33.0
          run_install: false
      - &setup-node
        name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ostool-server/webui/pnpm-lock.yaml

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env: &release_env
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release-plz-pr:
    name: Release-plz PR
    if: *release_condition
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - *setup-libudenv
      - *setup-pnpm
      - *setup-node
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env: *release_env
